# 1. 图像的基本操作

## 1.1 获取并修改像素值


In [1]:
import numpy as np
import matplotlib.pyplot as plt

import cv2


In [2]:
img = cv2.imread('./hycdn.jpeg')
# plt.imshow(img)
px = img[100, 100]
px

array([119, 147, 111], dtype=uint8)

In [3]:
blue = img[100, 100, 0]
blue

119

可以通过这种方式进行修改像素值

In [4]:
img[100, 100] = [255, 255, 255]
# plt.imshow(img)

获取和修改像素更好的方法

In [5]:
img.item(100, 100, 1)

255

In [6]:
img.itemset((100, 100, 1), 100)
img.item(100, 100, 1)

100

## 1.2 获取图像属性

In [7]:
img.shape  # np数组的形状，390 * 680 * 3 的数组

(390, 680, 3)

In [8]:
img.size  # np数组的数组大小

795600

In [9]:
img.dtype  # np数组的数据类型

dtype('uint8')

## 1.3 图像ROI

In [10]:
# plt.imshow(img)
jigsaw = img[50: 145, 480: 575]
jigsaw
# plt.imshow(jigsaw)
img[150:245, 380:475] = jigsaw
# plt.imshow(img)

## 1.4 拆分及合并图像通道

In [11]:
b, g, r = cv2.split(img)
b, g, r

(array([[  0,  13, 171, ..., 213,   0,   0],
        [  1,   5, 130, ..., 179,   0,  12],
        [174, 137, 191, ..., 246, 157, 209],
        ...,
        [ 87,  80, 124, ..., 145,  90,  99],
        [  3,   7,  92, ..., 129,   0,   0],
        [  0,   0,  94, ..., 140,   0,   0]], dtype=uint8),
 array([[  8,  29, 191, ..., 229,   7,   7],
        [ 14,  21, 150, ..., 195,  12,  28],
        [187, 153, 213, ..., 255, 173, 225],
        ...,
        [115, 108, 155, ..., 204, 148, 156],
        [ 31,  35, 123, ..., 185,  47,  40],
        [ 12,  12, 125, ..., 195,  18,  17]], dtype=uint8),
 array([[  0,   6, 168, ..., 211,   0,   0],
        [  0,   0, 127, ..., 177,   0,  10],
        [165, 130, 189, ..., 244, 155, 207],
        ...,
        [ 85,  78, 124, ..., 153, 100, 111],
        [  1,   5,  92, ..., 136,   4,   0],
        [  0,   0,  94, ..., 146,   0,   0]], dtype=uint8))

In [12]:
img2 = cv2.merge((b, g, r))
# plt.imshow(img2)

In [13]:
img2[:,:,0] = 0
# plt.imshow(img2)

## 1.5 为图像扩边（填充）

In [20]:
img3 = cv2.copyMakeBorder(img2, 10,10,10,10, cv2.BORDER_CONSTANT, value=(255,0,0))
# plt.imshow(img3)

# 2. 图像上的算术运算

## 2.1 图像加法

In [24]:
x = np.uint8([250])
y = np.uint8([10])
x, y

(array([250], dtype=uint8), array([10], dtype=uint8))

In [25]:
cv2.add(x, y)

array([[255]], dtype=uint8)

In [26]:
x + y

array([4], dtype=uint8)

## 2.2 图像混合

In [86]:
img1 = cv2.imread('WX001.png')
img2 = cv2.imread('WX002.png')
img3 = cv2.cvtColor(img1, cv2.COLOR_RGB2BGR)
img4 = cv2.cvtColor(img2, cv2.COLOR_RGB2BGR)
# plt.imshow(img4)

In [43]:
img1.size

120000

In [44]:
img2.size

120000

In [88]:
dst = cv2.addWeighted(img3, 0.3, img4, 0.7, 0)
# plt.imshow(dst)

## 2.3 按位运算

# 3. 程序性能检测及优化

## 3.1 使用 OpenCV 检测程序效率

In [67]:
e1 = cv2.getTickCount()
e2 = cv2.getTickCount()
time = (e2 - e1)/ cv2.getTickFrequency()
time

0.000111373

中值滤波效率检测

In [70]:
img1 = cv2.imread('hycdn.jpeg')
e1 = cv2.getTickCount()
for i in range(5,49,2):
    img1 = cv2.medianBlur(img1,i)
e2 = cv2.getTickCount()
t = (e2 - e1)/cv2.getTickFrequency()
t

0.582134366

## 3.2 OpenCV中的默认优化

In [71]:
cv2.useOptimized()

True

In [79]:
%timeit res = cv2.medianBlur(img,49)

29.1 ms ± 3.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [73]:
cv2.setUseOptimized(False)
cv2.useOptimized()

False

In [78]:
%timeit res = cv2.medianBlur(img,49)

26.4 ms ± 533 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [80]:
cv2.setUseOptimized(True)